name            = "st-games-api"
main            = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding       = "DB"
database_name = "st-games-ranking-db"
database_id   = "5c785a29-dab6-4b0d-beb2-e5557fac0397"
